version: '3.8'

services:
  evolution-api:
    image: atendai/evolution-api:v2.1.1
    restart: always
    ports:
      - "8080:8080"
    environment:
      # Server
      - SERVER_TYPE=http
      - SERVER_PORT=8080
      - SERVER_URL=${RENDER_EXTERNAL_URL}
      
      # Logs
      - LOG_LEVEL=ERROR
      - LOG_COLOR=false
      - LOG_BAILEYS=false
      
      # Database - usar MongoDB Atlas (configurar en variables de entorno)
      - DATABASE_ENABLED=true
      - DATABASE_CONNECTION_URI=${DATABASE_URL}
      
      # Redis (deshabilitado para simplificar)
      - REDIS_ENABLED=false
      
      # QR Code
      - QRCODE_LIMIT=30
      
      # Instance
      - INSTANCE_DELETE_STORE=false
      
      # Webhook Global
      - WEBHOOK_GLOBAL_ENABLED=true
      - WEBHOOK_GLOBAL_URL=${WEBHOOK_URL}
      - WEBHOOK_GLOBAL_WEBHOOK_BY_EVENTS=true
      
      # Authentication
      - AUTHENTICATION_TYPE=apikey
      - AUTHENTICATION_API_KEY=${API_KEY}
      
      # Language
      - LANGUAGE=es
      
      # Store
      - STORE_MESSAGES=true
      - STORE_MESSAGE_UP=true
      - STORE_CONTACTS=true
      - STORE_CHATS=true
    volumes:
      - evolution_instances:/evolution/instances
      - evolution_store:/evolution/store
    command: >
      sh -c "
        echo 'Starting Evolution API...' &&
        node ./dist/src/main.js
      "

volumes:
  evolution_instances:
  evolution_store:
